DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS coffeeorder;


CREATE TABLE customer(
  id INTEGER PRIMARY KEY,
  fullname VARCHAR(63) NOT NULL,
  points INTEGER NOT NULL DEFAULT 5,
  phone INTEGER(10) UNIQUE,
  email VARCHAr(255) UNIQUE,
  createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE coffeeorder(
  orderid INTEGER PRIMARY KEY,
  customerid INTEGER NOT NULL,
  redeemed BOOLEAN,
  orderdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  price FLOAT,
  FOREIGN KEY (customerid) REFERENCES customer(id)
);
